### ISSUE TITLE
svcrash.py gets an exception at line 137 (svn) because sport is not set

### ISSUE THREAD

**Issue by TrevorPH** [sandrogauci/sipvicious#33]
--- /usr/bin/svcrash.py.orig	2015-09-14 12:24:33.808985272 +0000
+++ /usr/bin/svcrash.py	2015-09-14 12:25:01.572005361 +0000
@@ -132,7 +132,10 @@
     def checknsend(self,pkt):
         data = str(pkt.getlayer(Raw))
         ipaddr = pkt.getlayer(IP).src
-        port = pkt.getlayer(UDP).sport
+	try:
+	        port = pkt.getlayer(UDP).sport
+	except AttributeError:
+		return
         src = ipaddr,port
         if not src in self.mytimer:
             #print "add %s:%s" % src

**Comment by TrevorPH** [comment]
github trashed my patch format :(

**Comment by sandrogauci** [comment]
happens .. and somehow I didn't get notified of your submission.. will apply the patch manually

**Comment by sandrogauci** [comment]
done .. thanks!
