### ISSUE TITLE
missing release tags / versions

### ISSUE THREAD

**Issue by nil0x42** [sandrogauci/sipvicious#34]
Hi, since migration of sipvicious to github, theres is no explicit release tag.
Upgrading packages in those conditions is particularly complicated.

I'd suggest to tag first git commit as version 0.2.8 (if it is really the case), and maybe provide a new release, if something stable apeared since this date.
I ll be glad to provide an up-to-date sipvicious package for archlinux as soon as version tags will be added here :)

Thanks in advance, and good luck for maintaning this awesome tool

**Comment by sandrogauci** [comment]
Hi @nil0x42 

you're right, I never actually released an update even if there were some commits. And the previous version releases were sortof lost. I have made v0.2.8 now available thanks to your suggestion. I will also release a new version at some point to integrate the new changes.

Tips always welcome =)

**Comment by sbrun** [comment]
Hi,
Latest tagged release was a long time ago. It would be nice to have a new release with all the changes. Thanks!

**Comment by sandrogauci** [comment]
Indeed. Will make it a new year's resolution ;-)
